name: .NET Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ./src/RdpProtocolHandler.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
      
    - name: Build application
      run: dotnet build $env:Solution_Name --no-restore --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Check code formatting
      run: dotnet format --check

    - name: Check code quality
      run: dotnet sonarscanner begin /k:"my_project_key" /d:sonar.host.url="https://my-sonarqube-server.com" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" && dotnet build ./src/RdpProtocolHandler.sln && dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Check dependencies for security vulnerabilities
      uses: depcheck/action@v1
      with:
        args: --fail-on-update --severity=high --severity=critical
        token: ${{ secrets.GITHUB_TOKEN }}
